# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodePunks
email: oi@codepunks.ru
description: > # this means to ignore newlines until "baseurl:"
  Digital production studio.<br> Производственная студия<br> интернет проектов.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://codepunks.ru" # the base hostname & protocol for your site
twitter_username: codepunksru
github_username:  codepunksru
# Or enter your Google Tag Manager web tracking code https://tagmanager.google.com (e.g. GTM-5RRMLA) to activate tracking
google-tag-manager: GTM-5BTCK4


# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap
